# Secrets récupérés depuis Vault au runtime
proxmox_site1:
  api_url: "{{ vault_proxmox_site1_url | default('https://S1-PROXMOX:8006/api2/json') }}"
  api_user: "{{ vault_proxmox_site1_user }}"
  api_password: "{{ vault_proxmox_site1_password }}"
  
proxmox_site2:
  api_url: "{{ vault_proxmox_site2_url | default('https://S2-PROXMOX:8006/api2/json') }}"
  api_user: "{{ vault_proxmox_site2_user }}"
  api_password: "{{ vault_proxmox_site2_password }}"