all:
  children:
    pfsense_s1:
      hosts:
        s1_pfsense:
          ansible_host: "{{ s1_pfsense_ip | default('10.10.10.10') }}"
          vmid: 106  # VMID réel fournie par l'école
          proxmox_node: "pve-s1"
      vars:
        vm_name: "s1-pfsense"
        vm_memory: 2048
        vm_cores: 2
        
    services_s1:
      hosts:
        s1_services:
          ansible_host: "{{ s1_services_ip | default('10.10.10.20') }}"
          vmid: 102
          proxmox_node: "pve-s1"
      vars:
        vm_name: "s1-services"
        vm_memory: 4096
        vm_cores: 2
        
    bastion_s1:
      hosts:
        s1_bastion:
          ansible_host: "{{ s1_bastion_ip | default('10.10.10.30') }}"
          vmid: 103
          proxmox_node: "pve-s1"
      vars:
        vm_name: "s1-bastion"
        vm_memory: 2048
        vm_cores: 2
